# Generated by Django 6.1.1 on 2026-10-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
    ]
