# Generated by Django 6.1.1 on 2026-10-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
