# Generated by Django 6.1.1 on 2026-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
